version: "3.9"
services:
  backend:
    container_name: bm-support-api
    build: .
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - .:/app
  db:
    image: postgres:latest
    container_name: bm-database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

volumes:
  dbdata:
    driver: local